name: Backend Test
on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd $GITHUB_WORKSPACE/backend && npm install
    - run: cd $GITHUB_WORKSPACE/backend && npm run build --if-present
    - run: cd $GITHUB_WORKSPACE/backend && npm test
